version: "3"

services:
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    command: sh -c "yarn dev"
    #command: tail -F anything
    volumes:
      - ./front:/app
      - node_modules
  backend:
    restart: always
    build:
        context: ./backend
    volumes:
      - ./backend:/app
    ports:
        - 3001:3001
    command: sh -c "yarn start:dev"
    #command: tail -F anything
    depends_on:
        - db
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - node_modules
